### ISSUE TITLE
zlog-mds: exclusive and shared mode optimizations

### ISSUE THREAD

**Issue by dotnwat** [michaelsevilla/malacology-popper#8] opened 2016-04-12 23:05 UTC

**Comment by dotnwat** [comment] 2016-04-14 00:25
@michaelsevilla fun with caps. i'm piggybacking on getattr and setattr. I was able to get a trace where one client is reading (e.g. a sequencer position locally... below that is issued=1), then I start another client that opens the same sequencer file with write permissions and then issued=0 which means the the client is now doing an MDS request per stat :)

```
2016-04-13 17:22:32.040043 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:32.040060 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=1
2016-04-13 17:22:33.040260 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:33.040278 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=1
2016-04-13 17:22:34.040473 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:34.040491 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=1
2016-04-13 17:22:35.040693 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:35.040711 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=0
2016-04-13 17:22:36.043813 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:36.043831 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=0
2016-04-13 17:22:37.046925 7ff3b1539ec0  3 client.4125 _getattr mask As issued=1
2016-04-13 17:22:37.046944 7ff3b1539ec0  3 client.4125 _getattr mask pAsLsXsFs issued=0
```

**Comment by dotnwat** [comment] 2016-04-14 01:52
perf difference between local and remote sequencer updates (ns)

```
lat: 77826  stat size: 0
lat: 60915  stat size: 0
lat: 50918  stat size: 0
lat: 57331  stat size: 0
lat: 3007632  stat size: 0
lat: 3348810  stat size: 0
lat: 3416270  stat size: 0

```

**Comment by michaelsevilla** [comment] 2016-05-08 04:46
@noahdesu: this is pretty much done -- I think we just need 2 paragraphs about how you implemented this (e.g., with `lseek()`) and then a paragraph in the results section about how we could re-use the MDS with a couple small tweeks and get all the robustness (lol), fault tolerance, client session handling, caching inodes, etc.

**Comment by michaelsevilla** [comment] 2016-05-08 04:57
Closing #24 and #40 -- as this seems to be a duplicate of this issue.

**Closed as completed** 2016-05-10 06:43 UTC
